### PR TITLE
ENH: table of CI results

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
The objective was just to have a centralized place with all of our build statuses, coverage, and code-health. This way we can know at a glance what our current status is.

**Comment by sbillinge** [comment]
I see, so whenever something is built somewhere or other in our code uinverse it gets summarized here, and if anything is broken anywhere we can see it in one place.  Is that the idea?  If this passes the cost-benefit analysis I support it.

What do you need in way of review for this particular PR?

**Comment by CJ-Wright** [comment]
Yes, that is the idea. The statuses are automatically updated as our CI builds. I can also include information from the packaging on conda-forge as well if that would be good. The only time we need to poke this file is when we add a new repo to the org.

If you are ok with things as they are then I'd like a merge (when I request review in general I think the code is ready for either comments or if none a merge).

**Comment by sbillinge** [comment]
Ok

**Pull request merged**
